### ISSUE TITLE
Integrate NFT smart contracts

### ISSUE THREAD

**Issue by manuelbenitez** [igorizviekov/nft_marketplace#36]
- [x] Mint NFT
- [x] List NFT
![image](https://github.com/igorizviekov/nft_marketplace/assets/20058638/1af7d5c2-cee4-4088-8fda-4dc8118a9352)

- [x] DeList NFT
![image](https://github.com/igorizviekov/nft_marketplace/assets/20058638/25a933be-9fe3-4e3d-a498-61e7dafc1b0e)

- [x] Buy NFT
![image](https://github.com/igorizviekov/nft_marketplace/assets/20058638/ee3a5678-e0b8-4809-86e6-8394af6399cb)

- [x] Is token listed method
![image](https://github.com/igorizviekov/nft_marketplace/assets/20058638/f426a32d-5af5-4d8f-ba9c-fb3cbd3dcf1c)

**Comment by igorizviekov** [comment]
**Mint NFT to a public Collection:**
1. Upload an image to IPFS
2. upload NFT metadata with image URI to IPFS
3. call the NFTMaretpalce contract mint function to mint an NFT, pass price, 1 as a collection (public Collection), and tokenURI
4. add a record to Logs DB

**List an NFT for sale:**
1. in a Collection contract mint NFT to a public collection `mint(1, tokenURI, price)` or create yours `createCollection(tokenURI)` and mint there using the same method
2. in NFTMarketplace contract call `listNFT(tokenId, newPrice)`
3. add a records to the Logs DB

**Purchase minted NFT:**
1. call `getNFTsInCollection` in Collections contract
4. call `buyBFT` method of Marketplace contract, pass tokenId, collectionId. tokenURI is not needed in this case
5. add a record to Logs DB

**Request a purchase for not minted NFT:**
1. get the Collection record from the DB
2. get a tokenURI from `record.nfts `array
6. call `buyNFT` method of Marketplace contract, pass 0 as a tokenId, collectionId, and tokenURI
7. Mint request created

**Approve mint request:**
1. get the record of a Collection from a DB
2. Get requestId from a `record.mintRequests`
3. call `approveMintRequest` and pass requestId
4. call `"/mint-request/close/:id"` API, pass requested. It will filter out this request from `mintRequests` for a Collection

**Render NFTs list in a private Collection:**
1. get a record for a Collection in the DB
2. get not minted list of NFTs from `record.nfts`
3. get the minted list of NFTs via the Collection contract by calling `getNFTsInCollection` or `getListedTokensInCollection`  method and passing `colectionRecord.tokenId` as a `collectionId`, `startIndex` (f.e. 0 to get the first ones, and `pageSize` for num of NFTs. It will return minted NFTs URIs
4. filter out minted tokenURIs from "not minted list"
5. get NFTs metadata from IPFS for both lists
6. Render a combined list on a page
7. For the NFT owner address  show list/delist btns for minted NFTs or "mint" btn for not minted
8. For other addresses show "Buy" btn for minted NFT or "Request a purchase" for not minted

**Render NFTs in a public Collection:**
1. get the list of NFTs of a public by calling `getListedTokensInCollection(1, startIndex, pageSize)`
2. get NFTs metadata from IPFS using received tokenURIs
3. For the NFT owner address render list/delist btns, for other addresses render "Buy" btn

**Render NFTs in a Collection owned by an address:**
1. get the list of NFTs of a public by calling `getListedTokensInCollection(1, startIndex, pageSize)`
2. filter NFTs by calling `collectionContract.ownerOf(tokenId)` for each item
3. get NFTs metadata from IPFS using received tokenURIs


**Bulk Upload NFTs to IPFS:**
1. collect images and metadata from the user
2. compose a ZIP file with the following structure:
 - in the "art" folder place all images
 - in the "metadata" folder place JSON files with NFT metadata
  - map images and their metadata using the same name for the file
 3. call `collections/ipfs/:id` endpoint and pass the ZIP file. It will upload data to IPFS and update relevant collection entry with tokenURIs
